# Generated by Django 3.1.2 on 2020-10-31 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(db_column='EMAIL', max_length=100, unique=True)),
                ('username', models.CharField(blank=True, db_column='USERNAME', max_length=100)),
                ('password', models.CharField(db_column='PASSWORD', max_length=100)),
                ('phone_number', models.CharField(db_column='PHONE_NUMBER', max_length=20)),
                ('full_name', models.CharField(blank=True, db_column='FULL_NAME', max_length=100, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE')),
                ('is_superuser', models.BooleanField(db_column='IS_SUPERUSER', default=False)),
                ('role', models.CharField(blank=True, choices=[('System Admin', 'System Admin')], db_column='ROLE', max_length=50, null=True)),
                ('image_url', models.CharField(blank=True, db_column='IMAGE_URL', default='', max_length=400)),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
            ],
            options={
                'db_table': 'XB_USER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArtExchangeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('user_id', models.CharField(db_column='USER_ID', max_length=20, unique=True)),
                ('email', models.CharField(db_column='EMAIL', max_length=100, unique=True)),
                ('phone_number', models.CharField(db_column='PHONE_NUMBER', max_length=20)),
                ('fullname', models.CharField(blank=True, db_column='FULLNAME', max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('Investor', 'Investor'), ('Issuer', 'Issuer')], db_column='USER_TYPE', max_length=50, null=True)),
                ('address', models.CharField(db_column='ADDRESS', max_length=255)),
                ('date_of_birth', models.DateField(db_column='DATE_OF_BIRTH')),
                ('bank_name', models.CharField(db_column='BANK_NAME', max_length=50, null=True)),
                ('bank_account_name', models.CharField(db_column='BANK_ACCOUNT_NAME', max_length=100, null=True)),
                ('bank_account_number', models.CharField(db_column='BANK_ACCOUNT_NUMBER', max_length=11, null=True)),
                ('wallet_account_number', models.CharField(db_column='WALLET_ACCOUNT_NUMBER', max_length=11)),
                ('bvn', models.CharField(db_column='BVN', max_length=12)),
            ],
            options={
                'db_table': 'XB_ART_EXCHANGE_USER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('account_number', models.CharField(db_column='ACCOUNT_NUMBER', max_length=10, unique=True)),
                ('fullname', models.CharField(db_column='FULL_NAME', max_length=200, null=True)),
                ('account_reference', models.CharField(db_column='ACCOUNT_REFERENCE', max_length=200, null=True, unique=True)),
                ('account_type', models.CharField(db_column='ACCOUNT_TYPE', max_length=20, null=True)),
                ('balance', models.DecimalField(db_column='BALANCE', decimal_places=2, default=0.0, max_digits=10)),
                ('bvn', models.CharField(db_column='BVN', max_length=12, null=True, unique=True)),
                ('bank', models.CharField(blank=True, choices=[('011', 'First Bank Plc'), ('014', 'Mainstreet Bank Plc'), ('023', 'CitiBank'), ('070', 'Fidelity Bank Plc'), ('050', 'Ecobank Nigeria Plc'), ('030', 'Heritage Bank Plc'), ('032', 'Union Bank of Nigeria Plc'), ('033', 'United Bank For Africa Plc'), ('232', 'Sterling Bank Plc'), ('035', 'Wema Bank Plc'), ('057', 'Zenith Bank Plc'), ('311', 'Parkway'), ('058', 'GTBank Plc'), ('214', 'First City Monument Bank Plc'), ('215', 'UnityBank Plc'), ('315', 'GTB Mobile Money'), ('082', 'Keystone Bank Plc'), ('084', 'Enterprise Bank Ltd'), ('063', 'Diamond Bank Plc'), ('044', 'Access Bank Nigeria Plc'), ('221', 'StanbicIBTC Bank Plc'), ('068', 'Standard Chartered Bank Nigeria Ltd'), ('322', 'Zenith Mobile'), ('323', 'Access Mobile'), ('401', 'ASO Savings and Loans'), ('304', 'Stanbic Mobile'), ('305', 'PAYCOM'), ('307', 'Ecobank Mobile'), ('309', 'FBN Mobile'), ('301', 'Jaiz Bank'), ('076', 'Polaris Bank'), ('101', 'Providus Bank'), ('100', 'Suntrust Bank'), ('102', 'Titan Trust Bank')], db_column='BANK', max_length=45, null=True)),
                ('restriction_type', models.CharField(choices=[('0', 'No restriction'), ('1', 'Debit restriction'), ('2', 'Credit restriction'), ('3', 'Debit and Credit restrictions')], db_column='RESTRICTION_TYPE', default='1', max_length=1)),
            ],
            options={
                'db_table': 'XB_BANK_ACCOUNT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('account_number', models.CharField(db_column='ACCOUNT_NUMBER', max_length=15)),
                ('transaction_type', models.CharField(db_column='TRANSACTION_TYPE', max_length=7)),
                ('narration', models.CharField(db_column='NARRATION', max_length=250)),
                ('time', models.DateTimeField(db_column='TIME', default=datetime.datetime.now)),
                ('amount', models.DecimalField(db_column='AMOUNT', decimal_places=2, max_digits=10)),
                ('transaction_reference', models.CharField(db_column='TRANSACTION_REFERENCE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'XB_BANK_TRANSACTION',
                'managed': True,
            },
        ),
    ]
