# Generated by Django 3.1.2 on 2020-11-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xendapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_column='IS_STAFF', default=False),
        ),
    ]
