# Generated by Django 3.1.2 on 2022-07-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xendapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blockchain_address',
            field=models.CharField(db_column='BLOCKCHAIN_ADDRESS', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blockchain_id',
            field=models.IntegerField(db_column='BLOCKCHAIN_ID', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blockchain_password',
            field=models.CharField(db_column='BLOCKCHAIN_PASSWORD', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blockchain_private_key',
            field=models.CharField(db_column='PRIVATE_KEY', max_length=300, null=True),
        ),
    ]
