# Generated by Django 3.1.2 on 2020-11-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xendapp', '0003_artlisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAssetTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('recipient_id', models.IntegerField(db_column='RECIPIENT_ID')),
                ('sender_id', models.IntegerField(db_column='SENDER_ID')),
                ('asset_name', models.CharField(db_column='ASSET_NAME', max_length=20)),
                ('quantity', models.IntegerField(db_column='QUANTITY')),
                ('unit_price', models.FloatField(db_column='UNIT_PRICE')),
                ('market_type', models.CharField(db_column='MARKET_TYPE', max_length=20)),
            ],
            options={
                'db_table': 'XB_PENDING_ASSET_TRANSFER',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='artexchangeuser',
            name='blockchain_address',
            field=models.CharField(db_column='BLOCKCHAIN_ADDRESS', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artexchangeuser',
            name='blockchain_id',
            field=models.IntegerField(db_column='BLOCKCHAIN_ID', null=True),
        ),
        migrations.AddField(
            model_name='artexchangeuser',
            name='password',
            field=models.CharField(db_column='PASSWORD', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='artexchangeuser',
            name='private_key',
            field=models.CharField(db_column='PRIVATE_KEY', max_length=300, null=True),
        ),
    ]
