# Generated by Django 3.1.2 on 2020-11-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xendapp', '0004_auto_20201103_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingassettransfer',
            name='recipient_id',
        ),
        migrations.AddField(
            model_name='pendingassettransfer',
            name='asset_issuer_id',
            field=models.IntegerField(db_column='ASSET_ISSUER_ID', null=True),
        ),
    ]
