# Generated by Django 3.1.2 on 2020-11-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xendapp', '0006_pendingassettransfer_recipient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingassettransfer',
            name='recipient_id',
        ),
        migrations.RemoveField(
            model_name='pendingassettransfer',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='pendingassettransfer',
            name='buyer_id',
            field=models.IntegerField(db_column='BUYER_ID', null=True),
        ),
        migrations.AddField(
            model_name='pendingassettransfer',
            name='seller_id',
            field=models.IntegerField(db_column='SELLER_ID', default=0),
            preserve_default=False,
        ),
    ]
