# Generated by Django 3.1.2 on 2020-11-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xendapp', '0007_auto_20201105_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='artlisting',
            name='blockchain_id',
            field=models.CharField(db_column='BLOCKCHAIN_ID', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='artlisting',
            name='qr_code',
            field=models.CharField(db_column='QR_CODE', max_length=255, null=True),
        ),
    ]
