# Generated by Django 3.1.2 on 2020-11-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xendapp', '0008_auto_20201105_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='artlisting',
            name='token_id',
            field=models.IntegerField(db_column='TOKEN_ID', null=True),
        ),
    ]
