# Generated by Django 3.1.2 on 2020-11-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xendapp', '0009_artlisting_token_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_type',
        ),
    ]
