# Generated by Django 3.1.2 on 2020-12-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xendapp', '0011_assettransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_image_url',
            field=models.CharField(blank=True, db_column='ID_IMAGE_URL', default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('System Admin', 'System Admin'), ('Investor', 'Investor'), ('Issuer', 'Issuer')], db_column='ROLE', max_length=50, null=True),
        ),
    ]
