# Generated by Django 3.1.2 on 2020-12-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xendapp', '0012_auto_20201217_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_name',
            field=models.CharField(blank=True, db_column='BANK_ACCOUNT_NAME', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, db_column='BANK_ACCOUNT_NUMBER', default='', max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, db_column='BANK_NAME', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='bvn',
            field=models.CharField(blank=True, db_column='BVN', default='', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_account_number',
            field=models.CharField(blank=True, db_column='WALLET_ACCOUNT_NUMBER', default='', max_length=11),
        ),
    ]
