# Generated by Django 3.1.2 on 2020-12-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xendapp', '0015_auto_20201218_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artlisting',
            name='security',
        ),
        migrations.AddField(
            model_name='artlisting',
            name='asset_id',
            field=models.CharField(db_column='ASSET_ID', default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artlisting',
            name='asset_type',
            field=models.CharField(choices=[('art', 'art'), ('real estate', 'real estate')], db_column='ASSET_TYPE', default='art', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artlisting',
            name='description',
            field=models.CharField(db_column='DESCRIPTION', default='descr', max_length=300),
            preserve_default=False,
        ),
    ]
