# Generated by Django 3.1.2 on 2020-12-18 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xendapp', '0016_auto_20201218_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artlisting',
            name='seller_id',
            field=models.ForeignKey(db_column='SELLER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
